name: Tests

on:
  push:
  pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Restore Composer cache
              uses: actions/cache@v2
              with:
                path: ./vendor
                key: vendor-${{ hashFiles('**/composer.lock') }}

            - name: Restore NPM cache
              uses: actions/cache@v2
              with:
                path: ./node_modules
                key: node_modules-${{ hashFiles('**/yarn.lock') }}

            - name: Restore Laravel cache
              uses: actions/cache@v2
              with:
                path: ./storage/framework/cache
                key: laravel-cache

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                coverage: none
                extensions: bcmath, curl, dom, exif, gd, iconv, imagick, intl, libxml, mbstring, pcntl, pdo, pdo_sqlite, soap, sqlite, zip

            - name: Install PHP dependencies
              run: composer install --no-ansi --no-interaction --no-progress --no-suggest --prefer-dist

            - uses: mirromutth/mysql-action@v1.1
              with:
                mysql version: latest
                mysql database: chirp_test
                mysql user: chirp
                mysql password: secret

            - name: Install JS dependencies
              run: |
                   yarn
                   yarn dev

            - name: Setup project
              run: |
                cp .env.ci.example .env
                php artisan key:generate

            - name: Run tests
              run: vendor/bin/phpunit
              env:
                TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
                TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
                TWITTER_TEST_USER_ID: ${{ secrets.TWITTER_TEST_USER_ID }}
                TWITTER_TEST_USER_NAME: ${{ secrets.TWITTER_TEST_USER_NAME }}
                TWITTER_TEST_USER_PASSWORD: ${{ secrets.TWITTER_TEST_USER_PASSWORD }}
                TWITTER_TEST_USER_TOKEN: ${{ secrets.TWITTER_TEST_USER_TOKEN }}
                TWITTER_TEST_USER_TOKEN_SECRET: ${{ secrets.TWITTER_TEST_USER_TOKEN_SECRET }}
